line-length = 120
target-version = "py314"

[lint]
select = ["E", "F", "I", "UP", "SIM"]

[lint.isort]
known-first-party = ["ansible_collections.verdel.rancher"]

[lint.per-file-ignores]
"plugins/inventory/rancher.py" = ["E402"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"